### PR TITLE
topological map change

### PR DESCRIPTION
**Pull request by Jailander**
mb_test8

### CODE REVIEW

**Comment by marc-hanheide** [comment]
can you elaborate what this does?

**Comment by Jailander** [comment]
The Start node and End node in the mb_test8 in the topological map were
Swapped, this PR switches them.

**Comment by cdondrup** [comment]
Actually the test didn't make sense before because the robot was just driving a meter forwards and passed the test. Now it is trapped in the end of a corridor and has to reach a waypoint in its back.

**Comment by Jailander** [comment]
Exact;ly and the test didn't make sense because the nodes were swapped :p

**Pull request merged**
