### PR TITLE
Add option to ScitosA5 to generate openni stack topics

### PR DESCRIPTION
**Pull request by nilsbore**
This adds a few things to be able to get all the topics of the normal openni camera in the simulator. The main drawback is that simulating the cameras in morse at this size and frequency is costly. However, I've found it to work out ok. The original settings are used if you do not set the flag when creating the robot. To run:
- Create a Scitosa5 robot in your scene with `Scitosa5(with_cameras = Scitosa5.WITH_OPENNI)`
- Launch `roslaunch strands_morse generate_camera_topics.launch`

If @kunzel could have a look at these changes before they are merge that would be great.

### CODE REVIEW

**Comment by hawesie** [comment]
@kunzel when you give it the ok I'll merge.

**Comment by nilsbore** [comment]
It would be great if someone could try this out, it works good for me and it improves how the cameras are modeled, with accurate focal lengths etc.

**Comment by hawesie** [comment]
Waiting on @kunzel

**Comment by nilsbore** [comment]
I just realized I forgot one thing. Since this uses the openni_wrapper stack to generate the topics, that has to be installed on the system. We should consider moving this from scitos_robot to another package since it is not really robot specific, and in this case will have other uses than just for a physical camera. I'll open an issue for that.

**Comment by cdondrup** [comment]
See: https://github.com/strands-project/scitos_robot/issues/33

**Comment by RaresAmbrus** [comment]
I think there is an open issue for that. I'll get on on Friday or next week Monday and move that package somewhere else.

**Comment by nilsbore** [comment]
Ok, thanks.

**Comment by kunzel** [comment]
Sorry, I completely forgot about this. I'll check it tonight or tomorrow. Thanks @nilsbore

**Comment by kunzel** [comment]
Nice work @nilsbore! Thanks a lot!

**Pull request merged**
