### PR TITLE
Update simulated laser pose to match real robot.

### PR DESCRIPTION
**Pull request by cburbridge**
Closes https://github.com/strands-project/strands_morse/issues/143.

### CODE REVIEW

**Comment by cburbridge** [comment]
Is there any way to have Jenkins run the navigation tests with this PR?

**Comment by Jailander** [comment]
To run them at jenkins I guess we would need to create a PR in strands_navigation after this has been merged (right @marc-hanheide ?) but you can run the tests on your workspace following the instructions here:
https://github.com/strands-project/strands_navigation/tree/indigo-devel/topological_navigation/tests

**Comment by marc-hanheide** [comment]
Yes, please run these separately. We can't have a full test in this repo

**Comment by marc-hanheide** [comment]
@Jailander can you comment? Did you try? I think we should merge this, as it certainly is not making things fail, but if it improves anything we need to still see.

**Comment by Jailander** [comment]
Yes I tried it didn't break as you said not sure it helps merge if you want

**Pull request merged**
