### PR TITLE
changed AAF sim to use full-scale openNI simulation 

### PR DESCRIPTION
**Pull request by marc-hanheide**
Thanks to #68 we can now do this and we should, to have all the image topics also in simulation. Thanks @nilsbore for this, but I had to also fix one thing in e7b6257f1ce892e15e591e8005a1768a23e9473d where I removed the machine tags from `generate_camera_topics.launch`. I think they are not needed, but I just want to confirm with @nilsbore.

Also, @Jailander, please comment if you think this is useful or has any side effects. I tested it locally and it's brilliant :smirk: 

apologies for the slightly off branch name...

### CODE REVIEW

**Comment by nilsbore** [comment]
@marc-hanheide As long as it works, I remember having to have the machine tag there for some reason. I'll try now and see if it works as expected.

**Comment by nilsbore** [comment]
At leas the colored point cloud does not work here any more, could be an issue with indigo, it complains that `[ERROR] [1427362626.320342550]: Depth image frame id [/head_xtion_depth_optical_frame] doesn't match RGB image frame id [/head_xtion_rgb_optical_frame]`. @marc-hanheide Does the colored point cloud work for you?

**Comment by marc-hanheide** [comment]
I have the same problem... did this work before? I didn't touch it

**Comment by marc-hanheide** [comment]
the error message also appear when I render the `/head_xtion/depth/points`... and not the registered one.

**Comment by nilsbore** [comment]
Yeah, I think I have a handle on this now, I'll see what I can do.

**Comment by marc-hanheide** [comment]
https://github.com/ros-drivers/openni2_launch/issues/9 ?

**Comment by marc-hanheide** [comment]
more specifically: https://github.com/ros-drivers/openni2_launch/issues/9#issuecomment-25433833 ?

**Comment by nilsbore** [comment]
The initial problem seems to be that the TF package did not accept frame IDs that start with `/` any more. If I remove the slash, I at least get the registered depth image to work. My problem now is that the images aren't synched time-wise so the openni wrapper has a problem to associate the frames. Hmm, all of this worked in hydro...

**Comment by marc-hanheide** [comment]
sorry... are you sure about the `/`? My understanding was that they are supposed to start with `/` and that ones without it are not officially working...

**Comment by nilsbore** [comment]
Yes, at least when I remove them from both camera frames, the transformations are working as they should. Otherwise TF it's complaining about the prepended `/`.

**Comment by marc-hanheide** [comment]
odd...

**Comment by nilsbore** [comment]
Rares' changed a thing in the code, that's why it's not working, we'll see if we can fix it.

**Comment by marc-hanheide** [comment]
bugger ;-)

**Comment by nilsbore** [comment]
https://github.com/strands-project/strands_morse/pull/114 details a fix.

**Comment by marc-hanheide** [comment]
So you're happy for this to be merged then?

**Comment by nilsbore** [comment]
Yes, as long as you merge my PR as well.
Den 26 mar 2015 12:41 skrev "Marc Hanheide" notifications@github.com:

**Pull request merged**
