### PR TITLE
[kth] Created a KTH simulator environment

### PR DESCRIPTION
**Pull request by nilsbore**
This pull request adds
- The sixth floor of our building as a blender file, `data/floorsix.blend`
- A script that creates the environment, `floorsix.py`
- A launch file that starts the script and the Scitos stuff needed, `launch/kth_floorsix.launch`
- A map of the floor built with gmapping, `maps/map.yaml`

Tested on my machine, will add furniture and stairs to the blend file when I have time.

### CODE REVIEW

**Comment by nilsbore** [comment]
@kunzel Can you merge this? Would be nice to have a KTH simulation environment as part of the release.

**Comment by kunzel** [comment]
OK, I will test it today.

**Comment by kunzel** [comment]
Oops, sorry @nilsbore. I totally forgot about this.

**Comment by nilsbore** [comment]
No problem! It's a bit barren but I'll work on putting some furniture in there. Where did you guys find models for tables etc?

**Comment by kunzel** [comment]
A lot of objects already come with morse. Some are already placed in environments:
https://github.com/strands-project/morse/tree/master/data/environments

Others are just in individual files:
https://github.com/strands-project/morse/tree/master/data/props

Just open the files with blender to to see what is there and what is missing. Alternatively, you can look out for new objects. There are a couple of open source blender libraries on the web.

**Pull request merged**
