### PR TITLE
adding move_base arena simulation

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by Jailander** [comment]
This is the map
arena
This is the arena it self
arena

**Comment by kunzel** [comment]
Seems good to me, so please merge.

**Comment by marc-hanheide** [comment]
as @Jailander is splitting the topo maps, we wait for that.

**Comment by marc-hanheide** [comment]
@jailander, shout out when this is deemed finalised.

**Comment by cdondrup** [comment]
@Jailander can you please change the position of the camera? Currently, if this is run on jenkins, not all the tests could be seen from the current pov. Is it possible to put the camera in the centre facing down so we see the whole arena?

**Comment by Jailander** [comment]
sure give me a minute

**Comment by marc-hanheide** [comment]
just noticed that this was missing install targets... @jailander

**Comment by Jailander** [comment]
#141 sorry

**Pull request merged**
