### PR TITLE
Added battery state sensor to robot (requires an up-to-date strands-project/morse!)

### PR DESCRIPTION
**Pull request by kunzel**
Added battery sensor to the robot and a docking station and label to the bham cs_lg enviroment. The robot can now charge its battery when it drives onto the docking station. The autonomous docking is almost working but needs some final tweaks. 
Please note that the battery state is only useful for planning as it has no influence on the robot control.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
is it safe to assume that people now have updated MORSE?

**Comment by kunzel** [comment]
Hmm, good question. Who else is currently using it? Lincoln, Bham, anyone else? 

The only problem is a single line of code where the new Battery state sensor is used. I could also change this for the old battery. But then the docking etc will not work...

**Comment by marc-hanheide** [comment]
I just tried it (updated MORSE first). Didn't work, but I probably did something wrong?:

```
[PRE-INITIALIZATION]
[    0.002] Python Version: 3.3.0
[    0.002] Blender Version: 2.65.0
[    0.002] Python path: ['/opt/strands/share/morse/data', '/opt/strands/share/morse/data/props', '/home/marc/workspace/catkin_ws/src/strands_morse/uol/data', '/opt/strands/share/morse/data/sensors', '/opt/strands/share/morse/data/actuators', '/home/marc/workspace/catkin_ws/src/strands_morse/strands_sim/robots', '/opt/strands/opt/blender/2.65/scripts/addons', '/opt/strands/opt/blender/2.65/scripts/startup', '/opt/strands/opt/blender/2.65/scripts/modules', '/home/marc/workspace/catkin_ws/src/strands_morse/uol/src', '/opt/strands/bin', '/opt/lib/python2.7/site-packages/pyscxml-0.8.3_20120108-py2.7.egg', '/opt/lib/python2.7/site-packages/restlib-0.9-py2.7.egg', '/opt/lib/python2.7/site-packages/suds-0.4-py2.7.egg', '/opt/lib/python2.7/site-packages/eventlet-0.13.0-py2.7.egg', '/opt/lib/python2.7/site-packages/Louie-1.1-py2.7.egg', '/opt/lib/python2.7/site-packages/greenlet-0.4.1-py2.7-linux-x86_64.egg', '/opt/lib/python2.7/site-packages/fsmtest-0.0.2-py2.7.egg', '/opt/lib/python2.7/site-packages/setuptools_lint-0.1-py2.7.egg', '/opt/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg', '/opt/lib/python2.7/site-packages/nosexcover-1.0.8-py2.7.egg', '/opt/lib/python2.7/site-packages/coverage-3.6-py2.7-linux-x86_64.egg', '/opt/lib/python2.7/site-packages/termcolor-1.1.0-py2.7.egg', '/opt/lib/python2.7/site-packages/logilab_astng-0.24.3-py2.7.egg', '/opt/lib/python2.7/site-packages/logilab_common-0.59.1-py2.7.egg', '/opt/strands/lib/python3.3/site-packages/distribute-0.6.49-py3.3.egg', '/opt/strands/lib/python3.3/site-packages/rospkg-1.0.20-py3.3.egg', '/home/marc/workspace/catkin_ws/src/strands_morse/uol/src', '/home/marc/workspace/catkin_ws/src/strands_morse/strands_sim/src', '/home/marc/workspace/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/strands/strands_catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/groovy/lib/python2.7/dist-packages', '/opt/lib/python2.7/site-packages', '/opt/strands/lib/python3.3/dist-packages', '/opt/strands/lib/python33.zip', '/opt/strands/lib/python3.3', '/opt/strands/lib/python3.3/plat-linux', '/opt/strands/lib/python3.3/lib-dynload', '/opt/strands/lib/python3.3/site-packages', '/opt/strands/lib/python3.3/site-packages/setuptools-0.6c11-py3.3.egg-info', '/home/marc/workspace/catkin_ws/src/strands_morse/uol/src', '/opt/strands/lib/python3.3/dist-packages', '/opt/strands/lib/python3.3/site-packages', '/opt/strands/opt/blender/2.65/python/lib/python33.zip', '/opt/strands/opt/blender/2.65/python/lib/python3.3/', '/opt/strands/opt/blender/2.65/python/lib/python3.3/plat-linux', '/opt/strands/opt/blender/2.65/python/lib/python3.3/lib-dynload', '/opt/strands/opt/blender/2.65/scripts/addons/modules', '/home/marc/.config/blender/2.65/scripts/addons/modules', '/opt/strands/lib/python3.3/site-packages/morse/blender', '/opt/strands/lib/python3.3/site-packages/morse/blender/human_interaction']
[    0.002] PID: 7079
[    0.003] No passive objects in the scene.
[    0.003] [robots.scitosA5] robot initialization
[    0.003] [robots.scitosA5] Component initialized
[    0.049] [sensors.laserscanner] robot.scan initialization
[    0.050] [sensors.laserscanner] Sick: Using arc object: 'Arc_180'
[    0.051] [sensors.laserscanner] Component initialized, runs at 10.00 Hz
[    0.051] Component robot.scan  added to robot
[    0.051] [sensors.odometry] Component initialized, runs at 60.00 Hz
[    0.052] Component robot.odometry (level: integrated) added to robot
[helpers.loading] Module not found: No module named 'morse.sensors.battery_state'
[helpers.loading] Could not load the class BatteryStateSensor in morse.sensors.battery_state
[helpers.loading] Could not create an instance of morse.sensors.battery_state.BatteryStateSensor
INITIALIZATION ERROR: the component 'robot' could not be properly initialized. Error when creating the class instance

[SUPERVISION SERVICES INITIALIZATION]

[SCENE INITIALIZATION]
INITIALIZATION FAILED!
[    0.052] Exiting now.
[COMPONENTS FINALIZATION]
[    0.052] [core.abstractobject] robot.odometry: I'm dying!!
[    0.052] [core.abstractobject] robot.scan: I'm dying!!
[    0.052] [core.abstractobject] robot: I'm dying!!
[CLOSING REQUEST MANAGERS...]
[    0.052] [core.services] Deleting all request managers...
[CLOSING DATASTREAMS...]
[CLOSING OVERLAYS...]
[EXITING SIMULATION]
Blender Game Engine Finished
```

**Comment by kunzel** [comment]
Did you also run cmake after your git pull? Otherwise the new files will not be copied. See my latest commit here: https://github.com/strands-project/strands_systems/commit/3773a7d9221b95230927aaf3903b16bb28fd2ad8

**Comment by marc-hanheide** [comment]
Bah! Why should I read the whole documentation... ;-) Works!

**Comment by marc-hanheide** [comment]
This shall be postponed for a few days to give people a chance to update their MORSE installation before we break the old setup with this merge.

**Pull request merged**
