### PR TITLE
[WIP] first tries to work on a multi-robot enviroment

### PR DESCRIPTION
**Pull request by marc-hanheide**
working towards simulating a number of individual robots in Morse... a lot of worked towards namespaces and tf prefixes is needed...

### CODE REVIEW

**Comment by marc-hanheide** [comment]
the topics seem to be all corrected now, if https://github.com/strands-project/scitos_apps/pull/163 and https://github.com/strands-project/strands_apps/pull/69 are merged, but the tf tree is still messed up.

Maybe, @kunzel, do you remember what I would have to do to allow it have several robots' tf prefixed consistently in Morse? Or maybe @severin-lemaignan

**Comment by severin-lemaignan** [comment]
@marc-hanheide would you have around a MWE for me to play with? I do not remember the details, I fear :-)

**Comment by marc-hanheide** [comment]
@severin-lemaignan I just couldn't find a multi-robot example in Morse... Look at https://github.com/strands-project/strands_morse/blob/ce5f035a27b3a7479e72cc298775e5302f56ed5c/strands_sim/src/strands_sim/builder/robots/scitosA5.py for my current robot builder, which is used in https://github.com/strands-project/strands_morse/blob/ce5f035a27b3a7479e72cc298775e5302f56ed5c/the_collection/collection_nocam_fast.py

Any hints would be welcome...

**Comment by severin-lemaignan** [comment]
I'll have a look if I find some time. I recommend you to drop an email on morse-users@laas.fr: someone might have some experience with that already.

**Comment by marc-hanheide** [comment]
@severin-lemaignan I figured it out myself in 4441592:
frames

**Comment by marc-hanheide** [comment]
now also needs https://github.com/strands-project/scitos_common/pull/62 merged

**Comment by severin-lemaignan** [comment]
@marc-hanheide woohoo! That's a massive TF tree! I've love to see a screenshot of the simulation :-D

**Comment by marc-hanheide** [comment]
image
here you go @severin-lemaignan

**Comment by severin-lemaignan** [comment]
@marc-hanheide cheers :-D

**Pull request closed without merging**
