### PR TITLE
Refactoring and catkinising of simulation to support multiple environments more transparently

### LINKED ISSUE #7: Catkinise repository and move execution and navigation somewhere else

### PR DESCRIPTION
**Pull request by marc-hanheide**
- added stuff to catkinise this repository (now strands_morse is the package, everythnig else is contained in it)
- the policy is that different environments can go into different subdirs (simulator.sh takes care of setting everything up)
- changed simulator.sh to set PYTHONPATH etc and removed this from the specific builder scripts
- move all non-simulation code (strands_executive) into subfolder TO-BE-MOVED for now (this should now be moved somewhere lese)
- created new environment tum_kitchen
- put everything that is common into strands_sim (robots, scripts, etc), make sure other environments can find what is in strands_sim
- documented new launch in README.md

this closes #7

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This is substantial refactoring, please check carefully! @cburbridge, please have a look, too.

**Comment by hawesie** [comment]
@cburbridge is on holiday this week, but I think @kunzel should be able to check things.

**Comment by kunzel** [comment]
Yes, I'll have a look at the changes.

**Comment by kunzel** [comment]
@marc-hanheide Good job! Thanks for tidying up. Here are some remarks:
-  the policy with subdirs provides a good structure and is a better solution wrt setting the MORSE_RESOURCE_PATH and the PYTHONPATH. However, it is also limited because every environment must be in a subdir which might cause problems if we want to use environments and or components from other projects.  
- I would still put a default.py into strands_sim in order to keep the MORSE file structure intact and to test the robot by running 'morse run/edit strands_sim'. But this can be quickly done. 
- The navigation is currently broken as strands_morse_2dnav is not a ROS package anymore. Maybe we should wait with merging the pull request until strands_morse_2d is moved to scitos_2dnavigation

**Comment by marc-hanheide** [comment]
Thanks for the feedback. Anybody working on scitos_2d yet? I agree that should be ready before we merge this. If you have a any idea to overcome the subdir limitation, let me know.

**Comment by hawesie** [comment]
Check the tickets in the patrolling repo.

**Comment by kunzel** [comment]
@marc-hanheide, @hawesie Now we have the URDF (scitos_common) and the 2D navigation config files (scitos_2d_navigation)  in separate repositories. Hence, I'd like to merge this pull request in. However, if I do it we wouldn't have the appropriate launch files for the simulation in place. I will only put the launch files and maps in their respective subdirectories in a next step. That is, after the merge you should not directly update your repository but wait until I've added the navigation related files. Is that OK wiht you?

**Comment by hawesie** [comment]
Sounds fine.

**Pull request merged**
